dataset_name: 'cervical'
dataset_root_path: 'dataset'
df_train: 'train_slides.csv'
df_trainval: 'train_val_slides.csv'
df_val: 'val_slides.csv'
df_test: 'test_slides.csv'
folder_train: ''
folder_val: ''
folder_test: ''
df_classid_classname: 'classid_classname.csv'
